#!/bin/sh
#
# busybox init script for loading nvdla dependencies
#

case "$1" in
  start)
    echo "Setting up nvdla"
    insmod /usr/share/opendla.ko
    ;;
  stop)
    echo -n "There is nothing to stop for nvdla"
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
